menu:
#  Home: /
#  Archives: /archives

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: UA-5531338-1

author_link: https://twitter.com/ashokgelal
